base = "ocean"
syntax = "base16-ocean.dark"

[ui]
toc_bg = "#1e2030"
toc_border = "#494d64"
content_bg = "#24273a"
scrollbar_hover = "#b7bdf8"
status_bg = "#181926"
status_separator = "#5b6078"
status_brand_fg = "#24273a"
status_brand_bg = "#c6a0f6"
status_filename_fg = "#cad3f5"
status_filename_bg = "#363a4f"
status_watch_fg = "#a6da95"
status_watch_bg = "#363a4f"
status_reloaded_fg = "#24273a"
status_reloaded_bg = "#a6da95"
status_search_fg = "#eed49f"
status_search_bg = "#363a4f"
status_success_fg = "#a6da95"
status_success_bg = "#363a4f"
status_warning_fg = "#eed49f"
status_error_fg = "#ed8796"
status_error_bg = "#363a4f"
status_shortcut_fg = "#939ab7"
status_percent_fg = "#b7bdf8"
toc_hover_fg = "#cad3f5"
toc_header_fg = "#939ab7"
toc_active_bg = "#363a4f"
toc_inactive_bg = "#1e2030"
toc_accent = "#c6a0f6"
toc_index_inactive = "#6e738d"
toc_primary_active = "#cad3f5"
toc_primary_inactive = "#b8c0e0"
toc_secondary_inactive = "#6e738d"
toc_secondary_text_active = "#b8c0e0"
toc_secondary_text_inactive = "#939ab7"

[markdown]
search_highlight_bg = "#494d64"
search_match_bg = "#eed49f"
code_gutter = "#6e738d"
blockquote_marker = "#939ab7"
list_level_1 = "#a6da95"
list_level_2 = "#8aadf4"
list_level_3 = "#f5bde6"
ordered_list = "#eed49f"
table_border = "#5b6078"
table_separator = "#494d64"
table_header = "#eed49f"
table_cell = "#cad3f5"
heading_1 = "#c6a0f6"
heading_2 = "#a6da95"
heading_3 = "#8aadf4"
heading_4 = "#f5bde6"
heading_other = "#f5a97f"
heading_underline = "#494d64"
code_frame = "#5b6078"
code_label = "#939ab7"
inline_code_fg = "#f5a97f"
inline_code_bg = "#363a4f"
rule = "#494d64"
link_icon = "#7dc4e4"
link_text = "#8aadf4"
link_hover = "#91d7e3"
blockquote_text = "#b8c0e0"
text = "#cad3f5"
strong_text = "#f4dbd6"
latex_inline_fg = "#f5bde6"
latex_inline_bg = "#363a4f"
latex_block_fg = "#f5bde6"
mermaid_keyword = "#f5a97f"
mermaid_arrow = "#8aadf4"
mermaid_label = "#a6da95"
mermaid_block_fg = "#cad3f5"
mark_fg = "#24273a"
mark_bg = "#eed49f"
task_checked = "#a6da95"
task_unchecked = "#939ab7"
alert_note = "#8aadf4"
alert_tip = "#a6da95"
alert_important = "#c6a0f6"
alert_warning = "#eed49f"
alert_caution = "#ed8796"
footnote_ref = "#7dc4e4"
footnote_text = "#b8c0e0"
