base = "forest"
syntax = "InspiredGitHub"

[ui]
toc_bg = "#f2efdf"
toc_border = "#bbc1aa"
content_bg = "#fffbef"
scrollbar_hover = "#606d00"
status_bg = "#ece7d5"
status_separator = "#8d927d"
status_brand_fg = "#fffbef"
status_brand_bg = "#606d00"
status_filename_fg = "#3d413d"
status_filename_bg = "#f2efdf"
status_watch_fg = "#606d00"
status_watch_bg = "#e4e8bd"
status_reloaded_fg = "#fffbef"
status_reloaded_bg = "#606d00"
status_search_fg = "#986500"
status_search_bg = "#f6e6bd"
status_success_fg = "#606d00"
status_success_bg = "#e4e8bd"
status_warning_fg = "#986500"
status_error_fg = "#b83e37"
status_error_bg = "#f8d4ca"
status_shortcut_fg = "#626a5c"
status_percent_fg = "#32618b"
toc_hover_fg = "#3d413d"
toc_header_fg = "#626a5c"
toc_active_bg = "#e4e8bd"
toc_inactive_bg = "#f2efdf"
toc_accent = "#b34d08"
toc_index_inactive = "#8d927d"
toc_primary_active = "#3d413d"
toc_primary_inactive = "#50564f"
toc_secondary_inactive = "#8d927d"
toc_secondary_text_active = "#50564f"
toc_secondary_text_inactive = "#626a5c"

[markdown]
search_highlight_bg = "#e4e8bd"
search_match_bg = "#f6e6bd"
code_gutter = "#8d927d"
blockquote_marker = "#8d927d"
list_level_1 = "#606d00"
list_level_2 = "#32618b"
list_level_3 = "#9d397c"
ordered_list = "#986500"
table_border = "#bbc1aa"
table_separator = "#ece7d5"
table_header = "#986500"
table_cell = "#3d413d"
heading_1 = "#b34d08"
heading_2 = "#606d00"
heading_3 = "#32618b"
heading_4 = "#9d397c"
heading_other = "#b83e37"
heading_underline = "#bbc1aa"
code_frame = "#bbc1aa"
code_label = "#626a5c"
inline_code_fg = "#b34d08"
inline_code_bg = "#f2efdf"
rule = "#bbc1aa"
link_icon = "#187252"
link_text = "#32618b"
link_hover = "#187252"
blockquote_text = "#50564f"
text = "#3d413d"
strong_text = "#3d413d"
latex_inline_fg = "#9d397c"
latex_inline_bg = "#f2dce7"
latex_block_fg = "#9d397c"
mermaid_keyword = "#b34d08"
mermaid_arrow = "#32618b"
mermaid_label = "#606d00"
mermaid_block_fg = "#3d413d"
mark_fg = "#3d413d"
mark_bg = "#f6e6bd"
task_checked = "#606d00"
task_unchecked = "#8d927d"
alert_note = "#32618b"
alert_tip = "#606d00"
alert_important = "#9d397c"
alert_warning = "#986500"
alert_caution = "#b83e37"
footnote_ref = "#187252"
footnote_text = "#50564f"
