# Starship prompt configuration
# Docs: https://starship.rs/config/

# Timeout for commands (ms)
command_timeout = 1000

# Newline between prompt lines
add_newline = true

# Prompt format
format = """
$directory\
([](fg:#3b315e)$git_branch$git_status$git_state[ ](bg:#3b315e)[](fg:#3b315e) )\
$python\
$java\
$nodejs\
$kotlin\
$kubernetes\
$azure\
$hostname\
$shlvl\
$jobs\
$status\
$cmd_duration\
$line_break\
$character"""

right_format = "$battery"

[character]
format = "$symbol "
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 0
truncate_to_repo = true
format = "[](fg:#394260)[ 󰉋 $path$read_only ]($style)[](fg:#394260) "
style = "bold fg:#c0caf5 bg:#394260"

[git_branch]
format = "[ $symbol$branch(:$remote_branch)]($style)"
symbol = " "
style = "bold fg:#c4b5fd bg:#3b315e"

[git_status]
format = '([ $all_status$ahead_behind]($style))'
style = "bold fg:#f5a97f bg:#3b315e"
conflicted = "≠"
ahead = "↑"
behind = "↓"
diverged = "↕"
up_to_date = ""
untracked = "?"
stashed = '\$'
modified = "•"
staged = "+"
renamed = "→"
deleted = "×"
typechanged = "~"

[git_state]
format = "[ $state( $progress_current/$progress_total)]($style)"
style = "bold fg:#eed49f bg:#3b315e"

[status]
disabled = false
format = "[$symbol$status]($style) "
symbol = "󰅙 "
style = "dimmed red"

[hostname]
ssh_only = true
format = "[@$hostname]($style) "
style = "dimmed yellow"

[shlvl]
disabled = false
threshold = 3
format = "[󰆍↳]($style) "
style = "dimmed cyan"

[jobs]
format = "[&·$number]($style) "
number_threshold = 1
style = "dimmed cyan"

[cmd_duration]
min_time = 2000
format = "[󰔟 $duration]($style) "
style = "dimmed yellow"

[battery]
format = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 40
style = "dimmed red"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[java]
format = '[${symbol}(${version} )]($style)'
symbol = " "

[nodejs]
format = '[${symbol}(${version} )]($style)'
symbol = "󰎙 "

[kotlin]
symbol = " "

[kubernetes]
disabled = true
format = '[$symbol$context( \($namespace\))]($style) '

[azure]
disabled = true
format = '[$symbol($subscription)]($style) '
