name = Everforest Light Contrast

bg = #f2efdf
panel = reset
border = #8d927d
fg = #3d413d
dim = #626a5c
accent = #32618b
cursor = #e4e8bd
selection = #e4e8bd
statusbar = #f2efdf
status_fg = #3d413d
mode_fg = #fffbef
mode_bg = #32618b
pri_a = #ad3430
pri_b = #b34d08
pri_c = #606d00
pri_d = #32618b
pri_other = #9d397c
project = #606d00
context = #b34d08
due = #986500
overdue = #ad3430
today = #ad3430
done = #626a5c
selected = #e4e8bd
matched = #986500
