# Everforest Light Hard Contrast for Superfile.

code_syntax_highlight = "everforest-light-hard"

full_screen_fg = "#3d413d"
full_screen_bg = "#fffbef"

gradient_color = ["#32618b", "#9d397c"]
directory_icon_color = "#32618b"

file_panel_fg = "#3d413d"
file_panel_bg = "#fffbef"
file_panel_border = "#8d927d"
file_panel_border_active = "#32618b"
file_panel_top_directory_icon = "#606d00"
file_panel_top_path = "#32618b"
file_panel_item_selected_fg = "#3d413d"
file_panel_item_selected_bg = "#e4e8bd"

footer_fg = "#50564f"
footer_bg = "#f2efdf"
footer_border = "#8d927d"
footer_border_active = "#606d00"

sidebar_fg = "#50564f"
sidebar_bg = "#fffbef"
sidebar_title = "#187252"
sidebar_border = "#8d927d"
sidebar_border_active = "#ad3430"
sidebar_item_selected_fg = "#3d413d"
sidebar_item_selected_bg = "#e4e8bd"
sidebar_divider = "#8d927d"

modal_fg = "#3d413d"
modal_bg = "#f8f5e4"
modal_border_active = "#32618b"
modal_cancel_fg = "#3d413d"
modal_cancel_bg = "#f8d4ca"
modal_confirm_fg = "#3d413d"
modal_confirm_bg = "#d8e7df"

help_menu_hotkey = "#32618b"
help_menu_title = "#9d397c"

cursor = "#b34d08"
correct = "#606d00"
error = "#ad3430"
hint = "#187252"
cancel = "#b34d08"
