#!/usr/bin/env bash
# Generated by linecraft. Do not edit by hand — edit the config and regenerate.
# Source config: linecraft builder
set -euo pipefail

input="$(cat)"
out=""
outgroup=""
now="${LINECRAFT_NOW:-$(date +%s)}"
sep="$(printf '\033[%sm%s\033[0m' '90' ' | ')"

append() {
  if [ -n "$1" ]; then
    if [ -n "$out" ]; then
      if [ -n "$2" ] && [ "$2" = "$outgroup" ]; then out="$out$3"; else out="$out$sep"; fi
    fi
    out="$out$1"
    outgroup="$2"
  fi
}

# segment: cwd (blue)
v="$(printf '%s' "$input" | jq -r '.workspace.current_dir // empty')"
if [ -n "$v" ]; then
  v=' '"$v"
  append "$(printf '\033[%sm%s\033[0m' '34' "$v")" '' ' '
fi

# segment: git (green)
v="${LINECRAFT_CMD_GIT-$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)}" || true
if [ -n "$v" ]; then
  v=' '"$v"
  append "$(printf '\033[%sm%s\033[0m' '32' "$v")" 'git' ' '
fi

# segment: model (yellow)
v="$(printf '%s' "$input" | jq -r '.model.display_name // empty')"
if [ -n "$v" ]; then
  append "$(printf '\033[%sm%s\033[0m' '33' "$v")" 'model' ' '
fi

# segment: effort (yellow)
v="$(printf '%s' "$input" | jq -r '.effort.level // empty')"
if [ -n "$v" ]; then
  append "$(printf '\033[%sm%s\033[0m' '33' "$v")" 'model' ' '
fi

# segment: context (white)
vc=''
cp="$(printf '%s' "$input" | jq -r '((.context_window.used_percentage // 0)) as $u | (([ (.rate_limits.five_hour.used_percentage // 0), (.rate_limits.seven_day.used_percentage // 0) ] | max | round)) as $r | ([$u,$r]|max|round)')"
if [ -n "$cp" ]; then
  if [ "$cp" -ge 80 ]; then vc='31'; elif [ "$cp" -ge 50 ]; then vc='33'; fi
fi
v="$(printf '%s' "$input" | jq -r --argjson now "$now" 'def k: if . >= 1000 then ((. / 1000) | round | tostring) + "k" else (. | tostring) end; def cd: if . <= 0 then "now" else . as $s | ($s/86400|floor) as $d | (($s%86400)/3600|floor) as $h | (($s%3600)/60|floor) as $m | if $d>0 then "\($d)d\($h)h" elif $h>0 then "\($h)h\($m)m" else "\($m)m" end end; .context_window as $cw | .rate_limits as $rl | ($cw.total_input_tokens) as $in | ($cw.context_window_size) as $size | ($cw.total_output_tokens) as $out | ([ (if $rl.five_hour.used_percentage != null then "Daily: \($rl.five_hour.used_percentage|round)%" else empty end), (if $rl.seven_day.used_percentage != null then "Weekly: \($rl.seven_day.used_percentage|round)%" else empty end) ] | if length>0 then " (" + join(", ") + ")" else "" end) as $ratelabel | ([ (if $rl.five_hour.resets_at != null and $rl.five_hour.resets_at > 0 then (($rl.five_hour.resets_at - $now)|cd) else empty end), (if $rl.seven_day.resets_at != null and $rl.seven_day.resets_at > 0 then (($rl.seven_day.resets_at - $now)|cd) else empty end) ] | if length>0 then " - Resets in " + join(" / ") else "" end) as $resetlabel | ((if $out != null and $out > 0 then " out:" + ($out|k) else "" end)) as $outpart | if $in != null and $size != null then "ctx:" + ($in|k) + "/" + ($size|k) + $ratelabel + $resetlabel + $outpart elif $ratelabel != "" then "ctx:" + $ratelabel + $resetlabel else empty end')"
if [ -n "$v" ]; then
  v=' '"$v"
  append "$(printf '\033[%sm%s\033[0m' "${vc:-37}" "$v")" '' ' '
fi

printf '%s' "$out"
