[catalogs]
searchPriorities = []
sortOrders = []

    [[catalogs.globalScopes]]
    catalogIdentifier = 'tuna.effects'

        [catalogs.globalScopes.scope]
        itemIDs = [ 'Confetti', 'Confetti Rain', 'Math', 'Rain', 'This is fine', 'WASTED' ]
        kind = 'only'

    [[catalogs.globalScopes]]
    catalogIdentifier = 'tuna.emoji'

        [catalogs.globalScopes.scope]
        kind = 'none'

[[comboMode.bindings]]
key = 's'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'tuna.applications//System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 't'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Applications/Utilities/Terminal.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'f'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Library/CoreServices/Finder.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'm'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Applications/Messages.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'n'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Applications/Notes.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'd'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:~/Downloads' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'h'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:~' ]
        type = 'savedCommand'

[hotkeys]
custom = []

    [hotkeys.app.activate]
    carbonKeyCode = 49
    carbonModifiers = 256

[settings]
screenPreference = 'activeWindow'
shelfCatalogEnabled = false
