# Everforest Light Contrast, derived from Everforest Light Hard.

theme[main_bg]="#fffbef"
theme[main_fg]="#3d413d"
theme[title]="#3d413d"
theme[hi_fg]="#32618b"
theme[selected_bg]="#e4e8bd"
theme[selected_fg]="#3d413d"
theme[inactive_fg]="#626a5c"
theme[graph_text]="#3d413d"
theme[meter_bg]="#ece7d5"
theme[proc_misc]="#187252"

theme[cpu_box]="#9d397c"
theme[mem_box]="#606d00"
theme[net_box]="#b34d08"
theme[proc_box]="#32618b"
theme[div_line]="#8d927d"

theme[temp_start]="#606d00"
theme[temp_mid]="#986500"
theme[temp_end]="#ad3430"

theme[cpu_start]="#187252"
theme[cpu_mid]="#32618b"
theme[cpu_end]="#9d397c"

theme[free_start]="#9d397c"
theme[free_mid]="#32618b"
theme[free_end]="#187252"

theme[cached_start]="#32618b"
theme[cached_mid]="#187252"
theme[cached_end]="#606d00"

theme[available_start]="#b34d08"
theme[available_mid]="#986500"
theme[available_end]="#606d00"

theme[used_start]="#606d00"
theme[used_mid]="#986500"
theme[used_end]="#ad3430"

theme[download_start]="#b34d08"
theme[download_mid]="#ad3430"
theme[download_end]="#9d397c"

theme[upload_start]="#606d00"
theme[upload_mid]="#187252"
theme[upload_end]="#32618b"

theme[process_start]="#32618b"
theme[process_mid]="#187252"
theme[process_end]="#606d00"

theme[proc_pause_bg]="#f8d4ca"
theme[proc_follow_bg]="#d8e7df"
theme[proc_banner_bg]="#f2dce7"
theme[proc_banner_fg]="#3d413d"
theme[followed_bg]="#d8e7df"
theme[followed_fg]="#3d413d"
