# Everforest Light Hard with locally adjusted contrast.

theme[main_bg]="#fffbef"
theme[main_fg]="#3d4c4f"
theme[title]="#3d4c4f"
theme[hi_fg]="#2c7198"
theme[selected_bg]="#e4e8bd"
theme[selected_fg]="#3d4c4f"
theme[inactive_fg]="#68766d"
theme[graph_text]="#3d4c4f"
theme[meter_bg]="#edeada"
theme[proc_misc]="#287f60"

theme[cpu_box]="#aa4d8e"
theme[mem_box]="#657a00"
theme[net_box]="#c65f18"
theme[proc_box]="#2c7198"
theme[div_line]="#9ca694"

theme[temp_start]="#657a00"
theme[temp_mid]="#a87700"
theme[temp_end]="#b83f3d"

theme[cpu_start]="#287f60"
theme[cpu_mid]="#2c7198"
theme[cpu_end]="#aa4d8e"

theme[free_start]="#aa4d8e"
theme[free_mid]="#2c7198"
theme[free_end]="#287f60"

theme[cached_start]="#2c7198"
theme[cached_mid]="#287f60"
theme[cached_end]="#657a00"

theme[available_start]="#c65f18"
theme[available_mid]="#a87700"
theme[available_end]="#657a00"

theme[used_start]="#657a00"
theme[used_mid]="#a87700"
theme[used_end]="#b83f3d"

theme[download_start]="#c65f18"
theme[download_mid]="#b83f3d"
theme[download_end]="#aa4d8e"

theme[upload_start]="#657a00"
theme[upload_mid]="#287f60"
theme[upload_end]="#2c7198"

theme[process_start]="#2c7198"
theme[process_mid]="#287f60"
theme[process_end]="#657a00"

theme[proc_pause_bg]="#f8d4ca"
theme[proc_follow_bg]="#d8e7df"
theme[proc_banner_bg]="#f2dce7"
theme[proc_banner_fg]="#3d4c4f"
theme[followed_bg]="#d8e7df"
theme[followed_fg]="#3d4c4f"
