# Everforest Light Hard with stronger foreground contrast
# Based on https://github.com/sainnhe/everforest/blob/master/palette.md

foreground              #3d413d
background              #fffbef
selection_foreground    #3d413d
selection_background    #d8e7df
cursor                  #b34d08
cursor_text_color       #fffbef
scrollbar_handle_color  #8d927d
scrollbar_track_color   #ece7d5
url_color               #32618b
active_border_color     #606d00
inactive_border_color   #8d927d
bell_border_color       #986500
active_tab_foreground   #3d413d
active_tab_background   #e4e8bd
inactive_tab_foreground #626a5c
inactive_tab_background #f2efdf
tab_bar_background      #ece7d5
mark1_foreground        #3d413d
mark1_background        #d8e7df
mark2_foreground        #3d413d
mark2_background        #f2dce7
mark3_foreground        #3d413d
mark3_background        #f6e6bd

color0  #3d413d
color8  #626a5c
color1  #b83e37
color9  #ad3430
color2  #606d00
color10 #606d00
color3  #986500
color11 #986500
color4  #32618b
color12 #32618b
color5  #9d397c
color13 #9d397c
color6  #187252
color14 #187252
color7  #bbc1aa
color15 #fffbef
