# Everforest Light Hard with stronger foreground contrast
# Based on https://github.com/sainnhe/everforest/blob/master/palette.md

foreground              #3d4c4f
background              #fffbef
selection_foreground    #3d4c4f
selection_background    #e4e8bd
cursor                  #c65f18
cursor_text_color       #fffbef
url_color               #2c7198
active_border_color     #657a00
inactive_border_color   #9ca694
active_tab_foreground   #3d4c4f
active_tab_background   #e4e8bd
inactive_tab_foreground #68766d
inactive_tab_background #f2efdf
tab_bar_background      #edeada

color0  #3d4c4f
color8  #68766d
color1  #c94f4c
color9  #b83f3d
color2  #657a00
color10 #657a00
color3  #a87700
color11 #a87700
color4  #2c7198
color12 #2c7198
color5  #aa4d8e
color13 #aa4d8e
color6  #287f60
color14 #287f60
color7  #bec5b2
color15 #fffbef
