alias ll='ls -lh'
alias la='ls -lAh'
alias lg='la | grep '
alias findg='find . | grep '
alias c=clear
alias ..='cd ..'
alias j='jobs -l'
alias more='less' # less is more
alias which='type -a'
alias path='echo -e ${PATH//:/\\n}'
